// Minimal hand-written types mirroring supabase/migrations/0001_init_schema.sql.
// Passing this as the generic to createClient() is what makes
// .from(table).insert()/.select() actually type-check against real
// columns — without it, supabase-js v2 has no way to know the row shape.
//
// Every table entry must satisfy postgrest-js's GenericTable shape (Row,
// Insert, Update, Relationships) and the schema itself must have Tables,
// Views, and Functions — leaving any of those out silently falls back to
// `never` for insert/update payloads instead of raising a clear error.
export type Database = {
  public: {
    Tables: {
      orders: {
        Row: {
          id: string;
          created_at: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          company: string | null;
          items: unknown;
          subtotal: number;
          discount_applied: boolean;
          total: number;
          payment_status: 'pending' | 'paid' | 'failed';
          paystack_reference: string | null;
          referral_code: string | null;
          needs_etims: boolean;
          kra_pin: string | null;
          kra_business_name: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          fbclid: string | null;
          is_test: boolean;
          order_source: 'website' | 'whatsapp';
          whatsapp_ref: string | null;
          payment_type: 'full' | 'deposit' | 'balance' | null;
          meta_status: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          company?: string | null;
          items: unknown;
          subtotal: number;
          discount_applied?: boolean;
          total: number;
          payment_status?: 'pending' | 'paid' | 'failed';
          paystack_reference?: string | null;
          referral_code?: string | null;
          needs_etims?: boolean;
          kra_pin?: string | null;
          kra_business_name?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          fbclid?: string | null;
          is_test?: boolean;
          order_source?: 'website' | 'whatsapp';
          whatsapp_ref?: string | null;
          payment_type?: 'full' | 'deposit' | 'balance' | null;
          meta_status?: string | null;
        };
        Update: Partial<Database['public']['Tables']['orders']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'orders_referral_code_fkey';
            columns: ['referral_code'];
            isOneToOne: false;
            referencedRelation: 'affiliates';
            referencedColumns: ['referral_code'];
          },
        ];
      };
      affiliates: {
        Row: {
          id: string;
          created_at: string;
          name: string;
          email: string;
          phone: string;
          social_handle: string | null;
          referral_code: string;
          // Generated by Postgres from referral_code (migration 0004): read-only.
          referral_link: string;
          status: 'active' | 'pending';
        };
        Insert: {
          id?: string;
          created_at?: string;
          name: string;
          email: string;
          phone: string;
          social_handle?: string | null;
          referral_code: string;
          status?: 'active' | 'pending';
        };
        Update: Partial<Database['public']['Tables']['affiliates']['Insert']>;
        Relationships: [];
      };
      cart_leads: {
        Row: {
          id: string;
          created_at: string;
          type: 'individual' | 'business';
          full_name: string;
          job_title: string | null;
          company: string | null;
          email: string;
          phone: string;
          items: unknown;
          total: number;
          message: string | null;
          needs_etims: boolean;
          kra_pin: string | null;
          kra_business_name: string | null;
          quote_requested: boolean;
          quote_requested_at: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          fbclid: string | null;
          is_test: boolean;
        };
        Insert: {
          id?: string;
          created_at?: string;
          type: 'individual' | 'business';
          full_name: string;
          job_title?: string | null;
          company?: string | null;
          email: string;
          phone: string;
          items: unknown;
          total: number;
          message?: string | null;
          needs_etims?: boolean;
          kra_pin?: string | null;
          kra_business_name?: string | null;
          quote_requested?: boolean;
          quote_requested_at?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          fbclid?: string | null;
          is_test?: boolean;
        };
        Update: Partial<Database['public']['Tables']['cart_leads']['Insert']>;
        Relationships: [];
      };
      referral_commissions: {
        Row: {
          id: string;
          created_at: string;
          affiliate_id: string;
          order_id: string;
          commission_amount: number;
          payout_status: 'unpaid' | 'paid';
        };
        Insert: {
          id?: string;
          created_at?: string;
          affiliate_id: string;
          order_id: string;
          commission_amount: number;
          payout_status?: 'unpaid' | 'paid';
        };
        Update: Partial<Database['public']['Tables']['referral_commissions']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'referral_commissions_affiliate_id_fkey';
            columns: ['affiliate_id'];
            isOneToOne: false;
            referencedRelation: 'affiliates';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'referral_commissions_order_id_fkey';
            columns: ['order_id'];
            isOneToOne: false;
            referencedRelation: 'orders';
            referencedColumns: ['id'];
          },
        ];
      };
      rate_limit_hits: {
        Row: {
          id: number;
          created_at: string;
          route: string;
          key: string;
        };
        Insert: {
          id?: number;
          created_at?: string;
          route: string;
          key: string;
        };
        Update: Partial<Database['public']['Tables']['rate_limit_hits']['Insert']>;
        Relationships: [];
      };
      // migration 0008
      whatsapp_refs: {
        Row: {
          code: string;
          created_at: string;
          last_clicked_at: string;
          first_button: string;
          first_section: string;
          first_page: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          fbclid: string | null;
          fbc: string | null;
          fbp: string | null;
          cookie_consent: boolean;
          is_test: boolean;
          referral_code: string | null;
        };
        Insert: {
          code: string;
          created_at?: string;
          last_clicked_at?: string;
          first_button: string;
          first_section: string;
          first_page?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          fbclid?: string | null;
          fbc?: string | null;
          fbp?: string | null;
          cookie_consent?: boolean;
          is_test?: boolean;
          referral_code?: string | null;
        };
        Update: Partial<Database['public']['Tables']['whatsapp_refs']['Insert']>;
        Relationships: [];
      };
      whatsapp_clicks: {
        Row: {
          id: number;
          created_at: string;
          code: string;
          button: string;
          section: string;
          page: string | null;
          is_test: boolean;
          meta_status: string | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          code: string;
          button: string;
          section: string;
          page?: string | null;
          is_test?: boolean;
          meta_status?: string | null;
        };
        Update: Partial<Database['public']['Tables']['whatsapp_clicks']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'whatsapp_clicks_code_fkey';
            columns: ['code'];
            isOneToOne: false;
            referencedRelation: 'whatsapp_refs';
            referencedColumns: ['code'];
          },
        ];
      };
      // migration 0009
      order_payments: {
        Row: {
          id: number;
          created_at: string;
          order_id: string;
          paystack_reference: string;
          payment_type: 'full' | 'deposit' | 'balance';
          amount: number;
          paid_at: string | null;
          is_test: boolean;
        };
        Insert: {
          id?: number;
          created_at?: string;
          order_id: string;
          paystack_reference: string;
          payment_type: 'full' | 'deposit' | 'balance';
          amount: number;
          paid_at?: string | null;
          is_test?: boolean;
        };
        Update: Partial<Database['public']['Tables']['order_payments']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'order_payments_order_id_fkey';
            columns: ['order_id'];
            isOneToOne: false;
            referencedRelation: 'orders';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
};
